# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            I'm Alp Eren
tagline:          'a human'
description:      'and this is my blog about software development and Linux.'
url:              https://aekarakus.github.io
baseurl:          '/blog'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Alp Eren KARAKUŞ'
  url:            https://aekarakus.github.io

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
#sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.

utterance:
  # Note: Make sure the repo is public, otherwise your readers will not be able to view the issues/comments.
  # Make sure the [utterances app](https://github.com/apps/utterances) is installed on the repo, otherwise users will not be able to post comments.
  #  If your repo is a fork, navigate to it's settings tab and confirm the issues feature is turned on.
  repo:  aekarakus/blog
  issue-term: title   # Choose the mapping between blog posts and GitHub issues. 
  theme: github-light # Choose an Utterances theme that matches your blog. 'github-light' is default

  ## Optional
  label:  blog-comments # Choose the label that will be assigned to issues created by Utterances.